### ISSUE TITLE
How can I test the new Multiplayer support via WebSockets?

### ISSUE THREAD

**Issue by ZaDarkSide** [d07RiV/diabloweb#68]
Hello, glad to see the project is advancing, I've seen multiplayer support has been implemented. My question is now is there any steps in order to test the multiplayer support?

**Comment by d07RiV** [comment]
It seems to be fully functional, but it needs a server, which I can only run locally atm. A secure (https) page requires a secure websocket server, which is quite a bit harder to set up.

I'll probably make a direct connection (WebRTC) available first.

You can compile it locally from

**Comment by d07RiV** [comment]
Multiplayer should be available for everyone now (1.0.27). Just type in game name and you're good to go!

**Comment by ZaDarkSide** [comment]
Are there any instructions on how to run a local server?

**Comment by d07RiV** [comment]
No server, it uses WebRTC for now, which is peer to peer with a global signal server (from PeerJS).

**Comment by ZaDarkSide** [comment]
I have tested it and works very nice via WebRTC, is there any plans to support a dedicated server via WebSockets also?

**Comment by d07RiV** [comment]
Well it works for me locally but I would have to add SSL support to make it work with the site.

The server can be built from the Server project in https://github.com/d07RiV/devilution (visual studio or gcc both work, requires boost 1.69 or so). I removed websocket support from the client though, at least for now.

**Comment by ZaDarkSide** [comment]
Maybe you should add a switch whether you want to compile with WebRTC support or WebSocket support. I could see people running an old school dedicated server, similar how battle.net worked. If it is not to big of a trouble maybe you can make this as reality.

**Comment by d07RiV** [comment]
Is there a need for it, considering you can already match globally based on game name? Or you want to see a list of games currently up? I think it would be easier to set up some server just to keep the game list.

The only real reason to use websockets is because they have better browser support and don't rely on certain ports being open.

**Comment by ZaDarkSide** [comment]
Well WebRTC is peer to peer, basically if the player that hosts the game leaves, the server is dead.
For a true dedicated server WebSockets are more appropriate, and will keep the game running even if all players leave the game. (at least that's the theory behind dedicated servers)

**Comment by d07RiV** [comment]
Well yes, though it wouldn't be too difficult to make RTC keep the game alive until everyone quits.

**Comment by OrangBuangan** [comment]
> I could see people running an old school dedicated server, similar how battle.net worked.

For Diablo 1 it was always peer to peer, battle.net was simply a list of currently running games.

**Comment by cojmar** [comment]
> > I could see people running an old school dedicated server, similar how battle.net worked.
> 
> For Diablo 1 it was always peer to peer, battle.net was simply a list of currently running games.

I do not think battle.net was simply a game list, pear to pear has a huge problem u need to be active on internet if your incoming ports are behind a router and are blocked u have a problem. A dedicated server (or a dedicated proxy) that is active on internet with opend ports makes the game joinable by any one, and i do not remember having a problem to join any battle.net game so that is proof  is not just a list of games.

**Comment by cojmar** [comment]
I tested this multiplayer version on local computer between fire fox and chrome and it works, i tested it over the internet between me and and a friend ant it says game not found we tried both to host i have active ip in internet DMZ on router i host some other stuff to and still game was not foundable, i tested the game on LAN and it works, so my conclusion u have a port problem over the internet and web socket maybe be a better solution.

**Comment by d07RiV** [comment]
Yes, Diablo 1 absolutely had a problem of needing open ports. Most games of that time did.

WebRTC uses several techniques to "punch holes" to avoid firewall/NAT issues, but it's not always reliable, and I do get the same issue sometimes when trying to connect with my phone. I'm still not sure if it's a problem with WebRTC in general or the server I'm using to connect, and I'm still considering making WebSocket an alternative, once I figure out how to host a server.

**Comment by d07RiV** [comment]
Allright, I got websocket server up and running, will try to add it as an alternative now.

**Comment by cojmar** [comment]
That sounds very good! And do not get me wrong u doing super nice job but this looks and is ok for an alpha version. 

But if u wanna make a "web diablo" that means it works over the internet and hosting it on a server is a must not just in git hub pages.

You need to have users, u need to have full multiplayer so any one can connect regarding he has or not incoming ports blocked simulate a mini battle.net, see game lists because if u play it on web u want multiplayer, if u want single player u can just play "devilution", also a huge problem that was small treated on another topic is the MPQ, every time i wanna play i have to chose the mpq form my hard so u can read it just from there, that is not a good solution. In "devilution" u put the mpq one time in the folder of the game and that's it u play it, so u need to have a better approach for example: to play u need login, make a free user upload the mpq at register, u validate the mpq so i'm not "illegal" just at register, after that the game needs to allow me to play the game from any where, i go to another comp i sign in with my account that was validated and i play no mpq on 2nd comp, now i know that is a hard task and can be done in many ways some are smoother some are not, for example u can unpack the all mpq make it mp3 and whatever and do not repack it use that files as they are from server, but do not give ppl access to the version until they registerd and to register u need to upload original mpq just for validation not for use. if u make ppl carry mpq wherever they wanna play dose not make it a viable web version, not even good for an electron version cause i can't put the mpq in electron folder and play i still need to select it every time.

So u need some server to simulate a battlent and u can host the web  sokets on it to and that will make it epic from my pov ofc.

**Comment by OrangBuangan** [comment]
> I do not think battle.net was simply a game list, pear to pear has a huge problem u need to be active on internet if your incoming ports are behind a router and are blocked u have a problem. A dedicated server (or a dedicated proxy) that is active on internet with opend ports makes the game joinable by any one, and i do not remember having a problem to join any battle.net game so that is proof is not just a list of games.

You are probably thinking about how it worked in Diablo 2. For Diablo 1 you can find many talks about what problem they had with Diablo 1 being peer to peer and why they decided to change it for Diablo 2.

> i go to another comp i sign in with my account that was validated and i play no mpq on 2nd comp, now i know that is a hard task and can be done in many ways some are smoother some are not, for example u can unpack the all mpq make it mp3 and whatever and do not repack it use that files as they are from server

This would still require a distribution license and only GOG has that.

The devilutionx team is planning to work on a server/client setup and has some basics there but it will probably be a long time before it is ready.

**Comment by d07RiV** [comment]
I tested server based websocket, out of the box it seems too slow and constantly displays the "loading" cursor. I'll try to bundle packets together and see how it works.

**Comment by d07RiV** [comment]
So I pushed a build with websockets, it works pretty poorly with more than 2 players, and awfully on phones. I might try to modify the netcode but idk how it will work out.

**Comment by ZaDarkSide** [comment]
Well you should have a dedicated server in nodejs maybe, that will handle all connections. I don't know what is the current setup. I can provide hosting if you need it.

**Comment by d07RiV** [comment]
It is in nodejs. I don't think the problem is latency, just the game works in a weird way with those "turn" packets. I don't think they're necessary at all but it would be hard to figure out how to get rid of them without breaking everything.

**Comment by ZaDarkSide** [comment]
Well Diablo1 was first made as a turn based game then, Blizzard decided to make it real-time as hack by making each turn take a small amount of time.
You can find more about it here: https://www.diabloii.net/blog/comments/how-diablo-evolved-from-turn-based-to-real-time

**Comment by d07RiV** [comment]
I would imagine the change was made long before multiplayer was added.

**Comment by cojmar** [comment]
> > I do not think battle.net was simply a game list, pear to pear has a huge problem u need to be active on internet if your incoming ports are behind a router and are blocked u have a problem. A dedicated server (or a dedicated proxy) that is active on internet with opend ports makes the game joinable by any one, and i do not remember having a problem to join any battle.net game so that is proof is not just a list of games.
> 
> You are probably thinking about how it worked in Diablo 2. For Diablo 1 you can find many talks about what problem they had with Diablo 1 being peer to peer and why they decided to change it for Diablo 2.
> 
> > i go to another comp i sign in with my account that was validated and i play no mpq on 2nd comp, now i know that is a hard task and can be done in many ways some are smoother some are not, for example u can unpack the all mpq make it mp3 and whatever and do not repack it use that files as they are from server
> 
> This would still require a distribution license and only GOG has that.
> 
> The devilutionx team is planning to work on a server/client setup and has some basics there but it will probably be a long time before it is ready. Before that it might also become possible to save the world in multiplayer so you can continue a game.

You can save MPQ in local storage as worst case scenario and run it from there, instea dusing imput type file to read a file from users hard disk.

Now regarding battle.net, i do not know how much u know about diablo 1,judging from your comments u do not seam to know to many things about battle.net and network and diablo 1, i may be wrong but your answer that battle.net is just a game list is kind of silly and u do not provide any solid argument for that. But to answer your question  i'm talking about diablo 1 not 2, and the funny thing is diablo 1 didn't had a TCP/IP network in it, if u played in "LAN" only option was IPX and direct cable connection, so assuming what u say is true that battle.net was just a game list my question to u is how u make an IPX connection over the internet having in mind in 1996 wasn't any TCP/IP wrapper around over IPX. Now hellfire on the other hand the expansion from sierra has TCP/IP over network instead of battle.net

So logical conclusion is that diablo 1 had inside a TCP/IP that was made just to work with battle.net and battle.net is not just a game list, now hellfire because was made by Sierra couldn't connect to battle.net but they exposed the TCP/IP protocol for peer to peer connections.

Another fun fact is if u had a good ISO with diablo 1 u could play free on battle.net because diablo 1 didn't had a cd key u just needed that ISO,now in the real world the ISO can be found even 2day on piratebay or even google so the MPQ propery to blizzard and GOG trademarks over a 1996 is a bad joke this game was free to play on battle.net since the invention of "Daemon Tools", and like i said if u wanna cover that aspect u can save the MPQ in local storage and use it from there like i said above there are more then one methods to fix the need to select an MPQ every time u wanna play, some are smoother some are not but is doable and is doable without having problems with the law.Also the game can have an option to have the MPQ near it so if i decide to port this in an electron i can put the MPQ there and play, if i decide to host it on my own risk with the MPQ given to public is my business i just need the option to be able to do it. 

Also if u put it in electron u can have a web socket to TCP/IP  proxy directly in electron and u can make an app that dose peer to peer connection over a real TCP/IP, also u can make dedicated servers and lots of other nice stuff, not some experimental protocol like webRTC yet fully stable and is in the work for some years now.

**Comment by d07RiV** [comment]
500MB is far too much for local storage. It does that with the shareware one, but browser won't let you load the full retail version like that.

It's not hard to check it, you can join a game and then close your connection to battle.net, you'll stay in that game.

And I still don't get your argument about hosting the MPQ online. Is't still their property, and your argument about TPB makes no sense. Surely you're not saying it's a legal organization?

If I put the whole thing in Electron, then what's the point? Might as well play the original game instead, then.

**Comment by ZaDarkSide** [comment]
Well TPB as long as it doesn't store any copyrighted material on their servers is technically legal, because the BitTorrent technology uses only hashes of the content to communicate with peers. What the peers are sharing can be legal or illegal, but it's their responsibility. As for storing the original files on a web server, the owner of the web server is responsible for it's content.

> In general, the copying and distribution of video games that are under copyright without authorization is considered a copyright violation (often called as software piracy).

> Through the Library of Congress, some key exemptions to the DMCA have been granted to allow for video game preservation. 

> * In the 2003 set of exemptions, the Library disallowed enforcement of the DMCA for "computer programs protected by dongles that prevent access due to malfunction or damage and which are obsolete" and for "computer programs and video games distributed in formats that have become obsolete and which require the original media or hardware as a condition of access".
> * In the 2015 exemptions, the Library granted permission for preservationists to work around copy-protection in games which required an authentication step with an external server that was no longer online prior to playing the game which otherwise did not require online connectivity; this specifically did not cover games that were based on a server-client mode like most massively-multiplayer online games (MMOs).
> * In the 2018 exemptions, the Library allowed for preservation and fair use of server-based games like MMos, permitting preservationists to offer such games where they have legally obtained the game's code within museums and libraries.

**Diablo1 might fall in one of these exceptions from DMCA.**

As for persistent storage in browser I can refer you to this article which describes what are the limits for each browser for each technology involved: https://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by OrangBuangan** [comment]
> You can save MPQ in local storage as worst case scenario and run it from there, instea dusing imput type file to read a file from users hard disk.

Ok, but then it would only work on the browser where you already selected it, but yeah maybe that would be an improvement.

> Now regarding battle.net, i do not know how much u know about diablo 1,judging from your comments u do not seam to know to many things about battle.net and network and diablo 1, i may be wrong but your answer that battle.net is just a game list is kind of silly and u do not provide any solid argument for that. But to answer your question i'm talking about diablo 1 not 2, and the funny thing is diablo 1 didn't had a TCP/IP network in it, if u played in "LAN" only option was IPX and direct cable connection, so assuming what u say is true that battle.net was just a game list my question to u is how u make an IPX connection over the internet having in mind in 1996 wasn't any TCP/IP wrapper around over IPX. Now hellfire on the other hand the expansion from sierra has TCP/IP over network instead of battle.net

You also do not provide much evidence for your assertions. I read the code of both Diablo and the reverse engineered Battle.net server. I also played a lot of Diablo 1 on Battle.net, even recently where I looked at the network traffic. If you don't, believe me, you can read the code here: https://github.com/pvpgn/pvpgn-server
Diablo 1 has UDP (it isn't normal to use TCP for games), but it is only accessible via Bnet (or hacked diabloui.dll/snp files). Not that it matters at all regarding if there was a dedicated server or not.

**Comment by cojmar** [comment]
> > Now regarding battle.net, i do not know how much u know about diablo 1,judging from your comments u do not seam to know to many things about battle.net and network and diablo 1, i may be wrong but your answer that battle.net is just a game list is kind of silly and u do not provide any solid argument for that. But to answer your question i'm talking about diablo 1 not 2, and the funny thing is diablo 1 didn't had a TCP/IP network in it, if u played in "LAN" only option was IPX and direct cable connection, so assuming what u say is true that battle.net was just a game list my question to u is how u make an IPX connection over the internet having in mind in 1996 wasn't any TCP/IP wrapper around over IPX. Now hellfire on the other hand the expansion from sierra has TCP/IP over network instead of battle.net
> 
> You also do not provide much evidence for your assertions. I read the code of both Diablo and the reverse engineered Battle.net server. I also played a lot of Diablo 1 on Battle.net, even recently where I looked at the network traffic. If you don't, believe me, you can read the code here: https://github.com/pvpgn/pvpgn-server
> Diablo 1 has UDP (it isn't normal to use TCP for games), but it is only accessible via Bnet (or hacked diabloui.dll/snp files). Not that it matters at all regarding if there was a dedicated server or not.

You are right on the UDP part, the correct term is socket, now what socket u use TCP UDP is another discution, now if u look here : 
https://us.battle.net/support/en/article/7842

Blizzard says diablo uses ports 6112-6119 on both TCP and UDP

Now a basic socket example i have 1 server in the middle of 2 clients, 1 client is host one joins , if both clients connect to server on a TCP/IP adn server acts just as a proxy passes data from one client to another none of the clients do not need a port open for incoming, but u may feel some speed gap, now in reality Diablo is not a shooter it can work on a TCP even if is slower then UDP how manny actions can u do in diablo in 1 second and how much data u need to send how much latency u need in a game that dose like 1 move per second if u put this questions u realis is doable on TCP even if is slower then UDP, and to do not have problems with routers and incoming ports u need a man in the middle that just serves as a connection bridge between the 2 clients that do not have an open port.

Regarding the MPQ if u need to carry a 500 mega file with u every time u wanna play the game on this principle u can carry devilution and do not need a web diablo in 1st place. Again local storage may not be best example i'm sure there are better solutions. But in reality if i wanna play this this game form anywhere in this version as it is now i have so save the mpq on a private web-server or in email, download it in computer then open the diablo web-site serve the MPQ and play, if i carry or save the MPQ some place i can just save devilution and do not use this version at all cause it introduces more steps and offers nothing extra, the idea of WEB is not to carry 500 mega files in your pocket u have them on the WEB.

**Comment by cojmar** [comment]
Now regarding 
https://github.com/pvpgn/pvpgn-server

I understand that some ppl made a server that outputs same result as battle.net but that is not a perfect reproduction on how battle.net works is not a valid example, cause if battle.net outputs some 
data and i make a server that outputs same data that dose not mean blizzard inside treats connection same way as my custom server, just the output is the same, in case of this project diablo 1 is a perfect clone as blizzard wrote it not an emulation.

**Comment by ZaDarkSide** [comment]
>  I also played a lot of Diablo 1 on Battle.net, even recently where I looked at the network traffic. If you don't, believe me, you can read the code here: https://github.com/pvpgn/pvpgn-server

PVPGN is a well known BNet Emulator, it's not BNet code reverse engineered. It's written from scratch to emulate the original BNet server.

**Comment by OrangBuangan** [comment]
> https://us.battle.net/support/en/article/7842
> 
> Blizzard says diablo uses ports 6112-6119 on both TCP and UDP
> 
> if both clients connect to server on a TCP/IP and server acts just as a proxy passes data from one client to another none of the clients do not need a port open for incoming, but u may feel some speed gap, now in reality Diablo is not a shooter it can work on a TCP even if is slower then UDP how many actions can u do in diablo in 1 second and how much data u need to send how much latency u need in a game that dose like 1 move per second if u put this questions u realize is doable on TCP even if is slower then UDP

No one is arguring against TCP being possible, devilutionx already has a TCP implemented where only the host player needs to have an open port. Also as you point out Blizzard says you need ports open, so it should be clear to you that isn't what they did for Battle.net.

> I understand that some ppl made a server that outputs same result as battle.net but that is not a perfect reproduction on how battle.net works is not a valid example, cause if battle.net outputs some
> data and i make a server that outputs same data that dose not mean blizzard inside treats connection same way as my custom server, just the output is the same, in case of this project diablo 1 is a perfect clone as blizzard wrote it not an emulation.

The point is that you can see from the network traffic it produces is just a list of other player's IP that you then connect directly to via peer to peer over UDP. If you think this is not how Battle.net works I'm sorry I cannot help you, you will have to sniff the packages your self to learn.

> PVPGN is a well known BNet Emulator, it's not official BNet server code reverse engineered. It's written from scratch to emulate the original BNet server.

https://en.wikipedia.org/wiki/Reverse_engineering#Reverse_engineering_of_protocols

**Comment by cojmar** [comment]
In reality, html5 dose not support sockets whatever it supports is websocket and u can't have UDP and TCP over a websocket, so u have to write some wrapper on websocket.

A UDP connection is like a radio broadcast whoever has antenna receives the signal.

A TCP connection is a client server connection u establish a connection with a server (like cable) and over it u can send and recive data, only the server needs to have port open.

Having this in mind, if u make a websocket wrapper whatever u sniff there dose not apply to the case where u write a custom server and a custom wrapper, because in the end u do not have the protocols u describe in HTML is just how u write the client wrapper and the server. 

And that has nothing to do how old diablo used to work, or whatever sniffs u do. You capture whatever diablo outputs and and from there u have to do a custom connection client server on tcp, peer to peer on TCP, UDP etc... whatever is it u have to do it because the original code works on some protocols u do not directly have in browser and this problem will remain. So in the end u need to write some custom stuff, that can be much smarter and done with less effort  then what your sniff tells u on an 1996 way of communication.

**Comment by cojmar** [comment]
So to cut this long conversation, if u wanna make a web diablo that is not just devilution and to be a viable solution u need to understant what an web app means.

1) You have a user and a password that u login with so u can access your data from anywhere based on some auth

2) Your save files aren't stored in Local Storage, are saved on the server because if i switch browser now i do not have my savings, if i use devilution i can put devilutiion on a stick and have my savings wherever i go, in this version if i clear the storage if i switch browser by by saved data, this is not a good practice for WEB.

3) When condor games went to Blizzard and they told blizzard they wanna do a turn based RPG, Blizzard said to them: OK, but it needs to have multiplayer and it needs to be real time.
So your WEB diablo needs to have multiplayer accessible by anyone in any condition,

4) You need to simulate some kind of battle.net so ppl can play on the WEB

5) You do not put ppl to carry 500 mega files with them, is not a viable option u need a better solution.

Conclusion: 
-If u do that 5 stuff u have a viable web diablo not just some deviltion for electron like it looks now cause every damn thing is local and if is local u can just put it in an electron and at least u know u can carry local storage with u and the MPQ.

-How ever u do this is not so important as long as u can achieve this, because in the end u wanna make a web port of the game, not some stand alone single player on local storage devilution in html5, that already exists is called devilution .

And again this looks amazing to see diablo in html5 is WOW do not get me wrong but is just an alpha and has some concepts anti WEB in it.

Now how to implement connection and all stuff we can talk for 1 week but in the end is irrelevant, if u think u can do it on UDP and all can connect with no problems do it but all it matters in the end is everyone to be able to connect to one another and do not get stuck in some 1996 concepts, that emulation of battle.net u showed earlier is irrelevant if the code inside it is not the same as blizzard wrote it, it works that is all it matters in the end.

**Comment by OrangBuangan** [comment]
@cojmar you missed my point, all I have said is that Diablo never had a dedicated server so a lot of code would have to be rewritten to do what you are suggesting. It appears as if you are debating things that no one is bringing up.

GitHub issues is not a good place to have debates and it is not good to suggest lots of unrelated changes in an issue, maybe you instead want to join the Discord chat to bring your opinions.

Please also read up on UDP, it is not simply broadcast: https://en.wikipedia.org/wiki/User_Datagram_Protocol

**Comment by d07RiV** [comment]
> As for persistent storage in browser I can refer you to this article which describes what are the limits for each browser for each technology involved: https://www.html5rocks.com/en/tutorials/offline/quota-research/

From what I remember, some browsers have flexible quotas, but the more you store the higher the risk of the browser deciding to wipe your storage when it thinks it needs more space. I think having to pick the MPQ every time is less of an annoyance than getting your saves deleted.

**Comment by cojmar** [comment]
If u wanna talk on discord give me some contact info, ofc u do not have to do anything, u missed my point, let me explain it to u simple. I'm a senior back end server developer whatever i told u about sockets i can do it, i have a working diablo 1 version on web for like 3-4 years, i'm working with sockets for more then 20 years, i wrote custom socket apps in : C++, Delphi, flash media server, PHP, node.js i even wrote a video chat from scratch.

Now the MPQ u are so afraid  can be rewrote in the end not to be blizzard or GOG property, if i hand draw all the images in game at higher resolution they aren't blizzard property anymore.

So if u think u wanna make some real web diablo give me a call and i'm wiling to do all server part just for diablo love, now regarding at hosting ZaDarkSide said can provide a server.

Any way my discord ID is : cojmar#2517
If u consider what i wrote here interesting and wanna do it call me.
