### ISSUE TITLE
Right click doesnt work like before.

### ISSUE THREAD

**Issue by Acrahaemon** [d07RiV/diabloweb#70]
Since i played the game, there wasnt any issues until now. I used the right click without any problem but since yesterday, it doesnt work well. I have to press the right click button all the time so i cant cast spells that way like i did before. Its not possible to teleport/cast spells without interrupting.

/e OnePlus 6

**Comment by d07RiV** [comment]
This was intentional, because most of the time when I used right click modifier I only needed it for one click. I felt this is really helpful for stuff like ID scrolls which can be wasted if you accidentally rightclick again.

However, I didn't consider spell casting, maybe I should find some middle ground here.

**Comment by Acrahaemon** [comment]
I got it. Holding the button works and fine for me. Thanks for advice and help!
