### ISSUE TITLE
multiplayer room

### ISSUE THREAD

**Issue by erion** [d07RiV/diabloweb#75]
Hello.
When I create a room in multiplayer, just to farm, leave and enter again, it says the room already exists. So I have to create with a different name.

You should shutdown rooms with no players or your server will meltdown =P

Great job btw.

**Comment by d07RiV** [comment]
I assume you're talking about the WebRTC (first option). It shows that error in case of any error with the server, because it can't tell the difference right now. I recently hosted my own PeerJS server instead of the public one, but it seems the latest version is unstable and crashes sometimes. I made a change that I think should fix it, and restarted the server, will see if it's stable enough now.

**Comment by sskras** [comment]
Could you please add more details about the failure to create a game?

**Comment by erion** [comment]
@sskras it worked for a bit, yday both options stop working. At least for me.
First option still with "game already existis"
and second one is showing timeout error.
@d07RiV probably something in last commit broke something. Since I was able to play after the download save implementation.

**Comment by michelcouto** [comment]
For me both are NOT working...
I have the same as you:

First option still with "game already existis"
and second one is showing timeout error.

**Comment by sskras** [comment]
Confirming. The first one never worked for me.
The second fails like for a month. The multiplayer server is down, I guess.

**Comment by d07RiV** [comment]
Yes, the server is currently down, sorry about that.

**Comment by michelcouto** [comment]
But how about the first option? It would be great to at least be able to create a multiplayer game (even if that doesn't work as multiplayer).
