### ISSUE TITLE
Full version works on notebook, doesn't work on android

### ISSUE THREAD

**Issue by lemellofonseca** [d07RiV/diabloweb#80]
I was able to use DIABDAT.MPQ file. (518MB) and it worked fine on my notebooks Chrome.

However, on my smartphone using Android and Chrome, It doesn't. It starts loading and appears an "oops this page can't be loaded" message.

BTW, is it possible to import my old character files from Diablo folder? 

And lastly, are spell's hotkeys available?

Thanks

**Comment by d07RiV** [comment]
Seems your phone runs out of memory or runs into some other issue that prevents it from loading full version.

Yes, you can drop save files on the page. I just added a save manager for more intuitive UI.

You can use spell hotkeys just as you would in desktop version.

**Comment by lemellofonseca** [comment]
Hi

Are there any pre-reqs to prevent OOM errors?

Where exactly do I need to drop saved files?

And about hotkeying spell's, in desktop version, you can dot it by pressing F5-F8. How does that work on mobile?

Thanks!

**Comment by d07RiV** [comment]
Not sure if you can do anything about it. It needs to keep the whole MPQ in memory, which is already a decent chunk of RAM, plus whatever the game itself requires. It supports a more compact form of MPQ using MP3 files instead of WAV, but I haven't made a tool that I use to make these MPQs public yet (it lets you squeeze the data down to ~230MB). That's somewhat complicated to make because code to transform WAV to MP3 is quite heavy.

Saved files can be selected the exact same way you'd select the MPQ. Or you can press the "manage saves" button which should appear on the main page now (though admittedly I only made it appear if you have at least one save already, which was an oversight, but shouldn't be hard to work around).

Yeah you don't have spell hotkeys on mobile and have to do all the clicking yourself, unfortunately. There's already a good amount of screen space used for mouse modes and potions for touch UI, not sure if I can squeeze in the spells there (and it would be much harder to integrate than potions).

**Comment by lemellofonseca** [comment]
Forgot to mention, I play multiplayer, so it would be for multiplayer characters. Is it possible? I didn't see an option to select the files

Spell hotkeys would be awesome, if could be added.

Thanks!

**Comment by lemellofonseca** [comment]
Worked with the new MPQ compress feature. Also was able to upload my desktop characters, it works perfectly

**Comment by AJenbo** [comment]
There is now a version for Android which uses significantly less memory and has full multiplayer support with the native desktop client: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
