### ISSUE TITLE
Restarted WebSocket multiplayer game stay connecting forever

### ISSUE THREAD

**Issue by sskras** [d07RiV/diabloweb#84]
![image](https://user-images.githubusercontent.com/7887758/63647869-22efa880-c730-11e9-87b8-4699e95e30de.png)

**Comment by sskras** [comment]
If I play WebSocket multiplayer for a longer time, then press `[NEW GAME]`, select the same hero, press `[Create Game]` and enter some name, the app shows animated `Connecting.....` like forever.

In the console I see this:

> WebSocket is already in CLOSING or CLOSED state.  **websocket.js:88**
> (anonymous) @ [websocket.js:88](https://d07riv.github.io/diabloweb/api/websocket.js#88)

Or this line in the repo:
https://github.com/d07RiV/diabloweb/blob/master/src/api/websocket.js#L88

**Comment by d07RiV** [comment]
The server wasn't running at the time. I'm still in the process of migrating my sites to a new server so it might be unstable for some time.

**Comment by sskras** [comment]
@AJenbo , you closed the issue that is still present. Why?

**Comment by AJenbo** [comment]
The issue is the server not running, so the nature of the problem isn't strictly technical, but more then that the general multiplayer issue is tracked by https://github.com/d07RiV/diabloweb/issues/99. When it is solved we can open new ones if there are still more specific issues present.

Having and issue that your car doesn't start during cold weather isn't helpful when you do not own a car.
