### ISSUE TITLE
Connection timed out. 

### ISSUE THREAD

**Issue by tiehr** [d07RiV/diabloweb#95]
Can't run multiplay

**Comment by lemellofonseca** [comment]
Same issue here for Server option.

When I choose Direct, it gives me "Game already exists" no matter which game name I give.

Would be awesome to have a Direct MP game option that work independently of Server.

**Comment by pakit999** [comment]
same. any help?

**Comment by quadur** [comment]
Both options give 503 error it seems that the servers are offline, are you planning on releasing the server code so people can host small office party servers for themselves?;)

`peerjs.min.js:848 WebSocket connection to 'wss://diablo.rivsoft.net/peerjs?key=peerjs&id=diabloweb_TEST&token=n63gjqw9b0a' failed: Error during WebSocket handshake: Unexpected response code: 503`

`websocket.js:2 WebSocket connection to 'wss://diablo.rivsoft.net/websocket' failed: Error during WebSocket handshake: Unexpected response code: 503`

**Comment by mrt123** [comment]
I imagine for every single person reporting issue here, must be a lot of people who don't use github or don't know about the project, but still are disappointed when servers are down. I wonder if you have any stats to know how many people were playing daily before the crash ?

**Comment by AJenbo** [comment]
Don't forget that you can host a multiplayer game yourself if you use the native version of DevilutionX :)

**Comment by pakit999** [comment]
DevilutionX is cool but I need a web version to play Diablo in my workplace with no admin rights :/

**Comment by tiehr** [comment]
When will it open? Please tell me the answer.

**Comment by sskras** [comment]
@AJenbo: can diabloweb connect to DevilutionX or vice versa?

**Comment by AJenbo** [comment]
No unfortunate not, diabloweb was branched from Devilution and not DevilutionX so they don't share anything other then the base game. Also afaik there would be some challenges regarding connecting between the two since the browser doesn't give you true raw tcp/upd sockets. But that could be overcome with a server that abstracted this.
Eventually we plan to port DevilutionX to the browser as well and look in to a server side infrastructure, so given enough time/right people the problem will be solved.

**Comment by AJenbo** [comment]
Duplicate https://github.com/d07RiV/diabloweb/issues/99
